import { useState, useEffect, useRef } from 'react';
import { Loader2, X, ShieldAlert } from 'lucide-react';

export default function TOTPEntryModal({ 
  onClose, 
  onSuccess 
}: { 
  onClose: () => void;
  onSuccess: (code: string) => Promise<void> | void; 
}) {
  const [code, setCode] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) {
      setError("Please enter a valid 6-digit code.");
      return;
    }

    setIsVerifying(true);
    setError('');

    try {
      await onSuccess(code);
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message || "Invalid code. Please try again.");
      setCode(''); 
      inputRef.current?.focus(); 
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
      <div className="bg-white dark:bg-slate-900 p-8 rounded-2xl w-full max-w-sm shadow-2xl border dark:border-slate-800 flex flex-col relative">
        <button 
          onClick={onClose} 
          className="absolute top-4 right-4 text-slate-400 hover:text-slate-800 dark:hover:text-white transition-colors"
        >
          <X size={20} />
        </button>

        {/* Header */}
        <div className="flex flex-col items-center text-center mb-6 mt-4">
          <div className="h-16 w-16 bg-blue-100 dark:bg-blue-900/30 rounded-full flex items-center justify-center mb-4">
            <ShieldAlert className="text-blue-600 dark:text-blue-400" size={32} />
          </div>
          <h2 className="text-2xl font-bold dark:text-white mb-2">Two-Factor Auth</h2>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Enter the 6-digit authentication code generated by your app.
          </p>
        </div>

        {/* Verification Form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <input 
              ref={inputRef}
              type="text" 
              maxLength={6}
              placeholder="000000" 
              value={code} 
              onChange={e => setCode(e.target.value.replace(/\D/g, ''))} // Strips out letters/symbols instantly
              disabled={isVerifying}
              className={`w-full p-4 border-2 rounded-xl dark:bg-slate-800 dark:text-white text-center font-mono text-3xl tracking-[0.5em] outline-none transition-colors ${
                error 
                  ? 'border-red-500 focus:border-red-600' 
                  : 'border-slate-200 dark:border-slate-700 focus:border-blue-500'
              }`}
              required 
            />
            {error && (
              <p className="text-sm text-red-500 text-center mt-2 animate-shake">
                {error}
              </p>
            )}
          </div>

          <button 
            type="submit" 
            disabled={isVerifying || code.length !== 6} 
            className="w-full bg-blue-600 hover:bg-blue-700 text-white py-3.5 rounded-xl font-bold flex items-center justify-center transition-colors disabled:opacity-50"
          >
            {isVerifying ? <Loader2 className="animate-spin" size={20} /> : "Verify Identity"}
          </button>
        </form>

      </div>
    </div>
  );
}