from datetime import datetime
import hashlib
import logging
import re
from typing import Any, Dict, List, Optional
import traceback

from fastapi import APIRouter, Depends, Header, HTTPException, Query, status
from fastapi.responses import HTMLResponse, Response
from passlib.context import CryptContext
from pydantic import BaseModel
from sqlalchemy import desc, func, or_
from sqlalchemy.orm import Session

# Adjust these imports according to your actual project structure
from app.api.dependencies import get_current_user
from app.core.database import SessionLocal, get_db
from app.core.security import generate_api_key_pair
from app.models.logs import LogEntry
from app.models.user import User
from app.schemas.logs import LogsCreate, LogsResponse

# Import the PDF generator logic
from app.api.v1.logging_app.report_generator import generate_pdf_report

router = APIRouter()
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
logger = logging.getLogger(__name__)


# ==========================================
# PYDANTIC RESPONSE SCHEMAS
# ==========================================


class PaginatedLogsResponse(BaseModel):
  data: List[LogsResponse]
  total: int
  page: int
  totalPages: int


class ReportRequest(BaseModel):
  logs: List[LogsResponse]
  model: str = "llama3.2"


# --- AUTO-SEED SERVICE API KEYS ---
def ensure_service_keys():
  db = SessionLocal()
  try:
    todo_raw_key = "QOVvH0w88V1s5Xs16P5i42Ykf21lw28ZILx09QF8Jhk"
    todo_hash = hashlib.sha256(todo_raw_key.encode()).hexdigest()
    if not db.query(User).filter(User.api_key_hash == todo_hash).first():
      db.add(
          User(
              email="todo-service@central.local",
              username="todo-application",
              hashed_password=pwd_context.hash("service-account-no-login"),
              api_key_hash=todo_hash,
              is_active=True,
              is_deleted=False,
          )
      )

    calc_raw_key = "dOVKcBnRpyQHG1ViyXU8-5YtXPYF6NhFvH2JMHkBh3g"
    calc_hash = hashlib.sha256(calc_raw_key.encode()).hexdigest()
    if not db.query(User).filter(User.api_key_hash == calc_hash).first():
      db.add(
          User(
              email="calculator-service@central.local",
              username="Calculator Application",
              hashed_password=pwd_context.hash("service-account-no-login"),
              api_key_hash=calc_hash,
              is_active=True,
              is_deleted=False,
          )
      )

    db.commit()
  except Exception as e:
    db.rollback()
    print(f"Error auto-seeding API keys: {e}")
  finally:
    db.close()


ensure_service_keys()


# --- VALIDATION DEPENDENCY (Used for /ingest) ---
def verify_token(x_api_key: str = Header(...), db: Session = Depends(get_db)):
  key_hash = hashlib.sha256(x_api_key.encode()).hexdigest()
  user = (
      db.query(User)
      .filter(
          User.api_key_hash == key_hash,
          User.is_active == True,
          User.is_deleted == False,
      )
      .first()
  )

  if not user:
    raise HTTPException(status_code=403, detail="Invalid API Key")
  return user


# --- 1. INGEST ENDPOINT ---
@router.post("/ingest", response_model=LogsResponse)
async def ingest_log(
    log_in: LogsCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(verify_token),
):
  log_data = log_in.model_dump()

  if "extra" in log_data and log_data["extra"] is not None:
    log_data["extra_attributes"] = log_data.pop("extra")

  if not log_data.get("user_id"):
    message = log_data.get("message", "")
    match = re.search(r"User '([^']+)'", message)

    if match:
      target_username = match.group(1)
      found_user = (
          db.query(User).filter(User.username == target_username).first()
      )

      if found_user:
        log_data["user_id"] = str(found_user.id)
      else:
        try:
          dummy_password_hash = pwd_context.hash("autogenerated-calculator-user")
          new_auto_user = User(
              email=f"{target_username}@calculator.local",
              username=target_username,
              hashed_password=dummy_password_hash,
              is_active=True,
              is_deleted=False,
          )
          db.add(new_auto_user)
          db.commit()
          db.refresh(new_auto_user)
          log_data["user_id"] = str(new_auto_user.id)
        except Exception as e:
          db.rollback()
          print(f"Error auto-creating user from log: {e}")
          log_data["user_id"] = None
    else:
      if getattr(current_user, "username", None) == "todo-application":
        log_data["user_id"] = None
      else:
        log_data["user_id"] = str(current_user.id)

  new_log = LogEntry(**log_data)
  db.add(new_log)
  db.commit()
  db.refresh(new_log)
  return new_log


# --- 2. KEY GENERATION ENDPOINT ---
@router.post("/generate-key")
async def generate_key(
    db: Session = Depends(get_db), current_user: User = Depends(get_current_user)
):
  raw_key, hashed_key = generate_api_key_pair()
  current_user.api_key_hash = hashed_key
  db.commit()

  return {
      "api_key": raw_key,
      "message": "Save this key now. It will not be shown again.",
  }


# --- 3. RETRIEVAL & DASHBOARD ---
@router.get("/", response_model=PaginatedLogsResponse)
async def get_logs(
    page: int = Query(1, ge=1, description="Page number"),
    limit: int = Query(
        50, ge=1, le=10000, description="Items per page"
    ),  # Increased max boundary to 10000
    level: Optional[str] = Query(None, description="Log level filter"),
    service: Optional[str] = Query(None, description="Service name filter"),
    service_name: Optional[str] = Query(
        None, description="Alternative service name filter"
    ),
    user_id: Optional[str] = Query(None, description="User ID filter"),
    search: Optional[str] = Query(None, description="Search query string"),
    start_date: Optional[datetime] = Query(
        None, alias="startDate", description="Start timestamp"
    ),
    end_date: Optional[datetime] = Query(
        None, alias="endDate", description="End timestamp"
    ),
    db: Session = Depends(get_db),
):
  query = db.query(LogEntry)

  if level and level.upper() != "ALL":
    target_level = level.upper()
    if target_level in ("WARN", "WARNING"):
      query = query.filter(LogEntry.level.in_(["WARN", "WARNING"]))
    elif target_level in ("ERROR", "FATAL"):
      query = query.filter(LogEntry.level.in_(["ERROR", "FATAL"]))
    else:
      query = query.filter(LogEntry.level == target_level)

  selected_service = service or service_name
  if selected_service and selected_service.upper() != "ALL":
    decoded_service = selected_service.replace("+", " ").strip().lower()
    no_spaces = decoded_service.replace(" ", "")
    hyphenated = decoded_service.replace(" ", "-")

    query = query.filter(
        or_(
            LogEntry.service_name.ilike(f"%{decoded_service}%"),
            LogEntry.service_name.ilike(f"%{no_spaces}%"),
            LogEntry.service_name.ilike(f"%{hyphenated}%"),
        )
    )

  if user_id and user_id.upper() != "ALL":
    query = query.filter(LogEntry.user_id == str(user_id))

  if start_date:
    query = query.filter(LogEntry.timestamp >= start_date)
  if end_date:
    query = query.filter(LogEntry.timestamp <= end_date)

  if search and search.strip():
    term = f"%{search.strip()}%"
    query = query.filter(
        or_(
            LogEntry.message.ilike(term),
            LogEntry.service_name.ilike(term),
            LogEntry.level.ilike(term),
            LogEntry.user_id.ilike(term),
        )
    )

  total_count = query.count()

  offset = (page - 1) * limit
  logs = (
      query.order_by(desc(LogEntry.timestamp)).offset(offset).limit(limit).all()
  )

  total_pages = (total_count + limit - 1) // limit if total_count > 0 else 1

  return {
      "data": logs,
      "total": total_count,
      "page": page,
      "totalPages": total_pages,
  }


@router.get("/dashboard", response_class=HTMLResponse)
async def dashboard(db: Session = Depends(get_db)):
  logs = db.query(LogEntry).order_by(desc(LogEntry.timestamp)).limit(50).all()

  html_content = """
    <h2>Recent Logs</h2>
    <table border='1'>
        <tr>
            <th>Time</th>
            <th>Level</th>
            <th>Service</th>
            <th>Machine ID</th>
            <th>User ID</th> 
            <th>Message</th>
        </tr>
    """

  for log in logs:
    html_content += f"""
        <tr>
            <td>{log.timestamp}</td>
            <td>{log.level}</td>
            <td>{log.service_name}</td>
            <td>{getattr(log, 'machine_id', 'N/A')}</td>
            <td>{log.user_id}</td> 
            <td>{log.message}</td>
        </tr>
        """

  html_content += "</table>"
  return html_content


# --- 4. SECURE PROXY ENDPOINT ---
@router.post("/proxy-ingest")
async def proxy_ingest_log(
    log_in: LogsCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
  log_data = log_in.model_dump()
  if "extra" in log_data and log_data["extra"] is not None:
    log_data["extra_attributes"] = log_data.pop("extra")

  log_data["user_id"] = str(current_user.id)

  new_log = LogEntry(**log_data)
  db.add(new_log)
  db.commit()
  db.refresh(new_log)
  return new_log


# --- 5. ANALYTICS SUMMARY ENDPOINT ---
@router.get("/analytics/summary")
@router.get("/summary")
async def get_log_summary(db: Session = Depends(get_db)):
  level_counts = (
      db.query(LogEntry.level, func.count(LogEntry.id))
      .group_by(LogEntry.level)
      .all()
  )
  service_counts = (
      db.query(LogEntry.service_name, func.count(LogEntry.id))
      .group_by(LogEntry.service_name)
      .all()
  )
  total_logs = db.query(LogEntry).count()

  return {
      "total_logs": total_logs,
      "level_distribution": dict(level_counts),
      "service_distribution": dict(service_counts),
  }


# --- 6. SYSTEM USERS ENDPOINT ---
@router.get("/system/users")
@router.get("/users")
async def get_system_users(db: Session = Depends(get_db)):
  users = db.query(User).filter(User.is_deleted == False).all()
  return [
      {
          "id": str(u.id),
          "username": getattr(u, "username", u.email),
          "email": u.email,
      }
      for u in users
  ]


# --- 6.1. LOG USERS ENDPOINT FOR DROPDOWNS ---
@router.get("/log-users")
@router.get("/system/log-users")
async def get_log_users(db: Session = Depends(get_db)):
  results = db.query(LogEntry.user_id).distinct().all()
  user_ids = [r[0] for r in results if r[0]]

  if not user_ids:
    return []

  users = db.query(User).filter(User.id.in_(user_ids)).all()

  return [
      {"user_id": str(u.id), "username": getattr(u, "username", u.email)}
      for u in users
  ]


# --- 7. SERVICES LIST ENDPOINT FOR DROPDOWNS ---
@router.get("/services")
@router.get("/system/services")
async def get_system_services(db: Session = Depends(get_db)):
  services = db.query(LogEntry.service_name).distinct().all()
  service_list = [s[0] for s in services if s[0]]
  return {"services": service_list}


# --- 8. PDF REPORT GENERATION ENDPOINT ---
@router.post("/generate-report")
async def generate_log_pdf_report(payload: ReportRequest):
  """Generates an A4 PDF report with direct error exposure and safe stream response."""
  if not payload.logs:
    raise HTTPException(
        status_code=400, detail="No log entries provided for reporting."
    )

  try:
    pdf_bytes = generate_pdf_report(payload.logs, payload.model)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                "attachment; filename=system_log_report.pdf"
            )
        },
    )
  except Exception as e:
    err_detail = traceback.format_exc()
    print("\n========== CRASH TRACEBACK ==========")
    print(err_detail)
    print("=====================================\n")
    raise HTTPException(
        status_code=500,
        detail=str(e) + " | Check server console for full traceback.",
    )